[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.publish]
  # Include only necessary files for deployment
  include = [
    "index.html",
    "products_info.json",
    "netlify.toml"
  ]
  # Exclude all other files and directories
  exclude = [
    "*",
    "!index.html",
    "!products_info.json",
    "!netlify.toml"
  ]